# Generated by Django 3.2.6 on 2021-08-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=1)),
                ('adress', models.CharField(max_length=200)),
                ('gender', models.BooleanField()),
                ('typeCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.typecustomer')),
            ],
        ),
    ]
