# Generated by Django 3.2.6 on 2021-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_adress_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.BooleanField()),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
